name: quotify
description: "Quotify is a sleek and elegant app designed to inspire you with random quotes from a variety of thought leaders, famous personalities, and literary figures. It uses a Database API to randomly select a quote upon each swipe. Users can also AI generate quotes- which is powered by Google's Gemini API."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  build_runner: ^2.4.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/applogo.png